language: bash

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    sources:
    - debian-sid # Needed for shellcheck
    packages:
    - shellcheck
    - python-docutils # Needed for rst2man

env:
  global:
    - secure: "IzaKWe8IvA2KcLb1G+AnisFMNNIShHtNQ5Yn7VqPkWd5XgwSs76PROpcLHtCv0/o4PcqRFb0JYLKfyTsK0dhkKHgefNW0Da1R52QnR3+dWNUmYHCyZ2qkkjS6Kt9Tit1pJNB+9dlMICJIUdCUgRKfiV/yVjlCaa34J5pyZqi7mP7i+MtrieAlU2gE8lbGQGuFMJvofCdNCmseVEK3BhBSr7HhkDvA/sZtRWCQc9Qn0RnYxyIt0HQNnQjPfqZ8cCWXFo/EC6Ayq0ZdcWQAG/FiIjXxPR4UfDqdkDEGTJ87LE4i+37Q2FxGSb/gxHtWzUBTwyqEmDlcpmVxeV3wsNJ6x8JoVKLX04l795LSmiMZ1K0nwUbh+NbivhZutXACJi9IZzfXCAzAeJCoWmbsLrvx75qJ4l7yRXuflKxD0vtMTsEdqGrOe9NwvIEhbTq06NjTazRDjOLVHbKZmPdx7LqMHfA2YiP5tNzHhuV1q6ty0hZ2hRRbkovOl7PIXEae0XCLLiahYyhV5MgNBlq3nuP3SosKHILTWeUMqAXPmFs8U/8cr5CABEzxwKOOPZBUdGc1iylj+tR6rnJ+F/96ZvpV74Vwt1/9PqE45nVgIX3sjO6iQPCmq3zSWNtyT4F8fCcMFYBnNDoyTxD9i4XMiAf/xgYf2bMs0wYk57XopdUAK8="
  matrix:
    - DIST=regular DEPLOY_FILE=butt-*.tar.gz
    - DIST=single DEPLOY_FILE=butt.sh

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew tap homebrew/dupes
      brew install shellcheck docutils
      ln -s /usr/local/bin/rst2man.py /usr/local/bin/rst2man
      brew reinstall coreutils gnu-sed gnu-getopt
      export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
      export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
      export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
    fi
  - export PREFIX=$HOME/opt
  - mkdir -p $PREFIX/bin
  - export PATH=$PREFIX/bin:$PATH

before_script:
  - |
    if [[ $DIST == regular ]]; then
      ./configure \
        && make \
        && cat compiled/install \
        && compiled/install \
        || return $?
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PREFIX=/usr/local make dist; fi
    fi
  - |
    if [[ $DIST == single ]]; then
      ./configure \
        && make distsingle \
        && cp butt.sh $PREFIX/bin/butt
    fi

script:
  - shellcheck butt
  - butt --verbose -w test test/test.butt

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "$DEPLOY_FILE"
    skip_cleanup: true
    file_glob: true
    on:
      repo: InternetGuru/butt
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - deploy:
    provider: script
    script: "scripts/changelog-latest CHANGELOG.md | scripts/travis-update-release"
    on:
      repo: InternetGuru/butt
      tags: true
      condition: $TRAVIS_OS_NAME = linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
